#!/bin/sh

case "$1" in
    configure)
        mkdir -p \
            /opt/zimbra/data/ldap/state/run \
            /opt/zimbra/data/ldap/config \
            /opt/zimbra/data/ldap/mdb/db
        chown -R zimbra:zimbra /opt/zimbra/data/ldap
    ;;
esac

#DEBHELPER#

exit 0
